name: 'publish'

on:
  push:
    branches:
      - dev

jobs:
  publish-tauri:

    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'ubuntu-22.04'
            args: ''
#          - platform: 'windows-latest'
#            args: ''

    runs-on: ${{ matrix.platform }}
    environment: PROD
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: yarn install # or npm/pnpm/bun based on your setup

      # Read the changelog file into a variable
      - name: Read changelog
        id: changelog
        run: |
          echo "RELEASE_BODY<<EOF" >> $GITHUB_ENV
          cat CHANGELOG.md
          cat CHANGELOG.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo ${{ env.RELEASE_BODY }}

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: app-v__VERSION__
          releaseName: 'App v__VERSION__'
          releaseBody: ${{ env.RELEASE_BODY }} # Use the changelog content as the release body
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
