name: Build and Release Dockyard

on:
  push:
    branches:
      - release
    tags:
      - 'v*.*.*'
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install libwebkit2gtk-4.0-dev \
              build-essential \
              curl \
              wget \
              file \
              libssl-dev \
              libgtk-3-dev \
              libayatana-appindicator3-dev \
              librsvg2-dev
              
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Use the Node.js version compatible with your project

      - name: Install dependencies
        run: npm install

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: Install Tauri CLI
        run: cargo install tauri-cli

      - name: Build the Tauri app for Linux
        run: npm run tauri build

      - name: Package the app
        run: |
          mkdir release_builds
          cp src-tauri/target/release/bundle/appimage/dockyard_0.0.0_amd64.AppImage ./release_builds/
          cp src-tauri/target/release/bundle/deb/dockyard_0.0.0_amd64.deb ./release_builds/
          cp src-tauri/target/release/bundle/rpm/dockyard-0.0.0-1.x86_64.rpm ./release_builds/
          

      - name: Upload the build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dockyard-build
          path: release_builds/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dockyard-build

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release_builds/dockyard_0.0.0_amd64.AppImage
            release_builds/dockyard_0.0.0_amd64.deb
            release_builds/dockyard-0.0.0-1.x86_64.rpm
          tag_name: ${{ github.ref_name }}  # Uses the tag name from the push event
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
